# Staging environment values
namespace: staging

replicaCount: 1
image:
  repository: amokscience/hello
  pullPolicy: IfNotPresent
  tag: "dev-latest"

env:
  HTTP_PORT: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

ingress:
  enabled: true
  host: staging.hello.local

serviceAccount:
  create: true
  name: hello

autoscaling:
  enabled: false

externalSecrets:
  enabled: true
  awsRegion: us-west-2
  secretName: hello-staging-secrets
  awsSecrets:
    secretName: eso-secret-hello
  serviceAccountName: hello
