# Dev environment values
namespace: dev

replicaCount: 1
image:
  repository: amokscience/hello
  pullPolicy: Always
  tag: "dev-4311a71"

env:
  HTTP_PORT: 8050

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

ingress:
  enabled: true
  host: dev.hello

serviceAccount:
  create: true
  name: hello

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

externalSecrets:
  enabled: true
  awsRegion: us-west-2
  secretName: hello-dev-secrets
  awsSecrets:
    secretName: eso-secret-hello

monitoring:
  enabled: true
