apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

namespace: dev

patchesJson6902:
- target:
    group: v1
    version: v1
    kind: Service
    name: hello
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 8050

configMapGenerator:
- name: hello-config
  literals:
  - environment=dev
  - hello=Hello from dev Kubernetes!
