apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: qa-

namespace: qa

configMapGenerator:
- name: sql-service-config
  literals:
  - environment=qa
