# Staging environment values
namespace: staging

replicaCount: 1
image:
  repository: amokscience/knfo
  pullPolicy: IfNotPresent
  tag: "staging-89a963d"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

ingress:
  enabled: true
  host: staging.knfo.local

externalSecrets:
  enabled: false
