# Dev environment values
namespace: dev

replicaCount: 1
image:
  repository: amokscience/knfo
  pullPolicy: IfNotPresent
  tag: "dev-30f1ea1"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

serviceAccount:
  create: true
  name: knfo

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: dev.knfo.local

externalSecrets:
  enabled: false

monitoring:
  enabled: true
