# QA environment values
namespace: qa

replicaCount: 1
image:
  repository: amokscience/knfo
  pullPolicy: IfNotPresent
  tag: "qa-latest"

env:
  HTTP_PORT: 8070

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

ingress:
  enabled: true
  host: qa.knfo.local

externalSecrets:
  enabled: false
