{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "counting.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "counting.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "counting.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{- end }}
