apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knfo.fullname" . }}
  labels:
    {{- include "knfo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "knfo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "knfo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "knfo.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.env.HTTP_PORT }}
          protocol: TCP
        env:
        - name: HTTP_PORT
          value: "{{ .Values.env.HTTP_PORT }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
