{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: knfo-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: knfo-aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretResourceName }}
    creationPolicy: Owner
  data:
  - secretKey: knfo-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecretsManagerKeys.knfoApiKey }}
      property: knfo
{{- end }}
