apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-end.fullname" . }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "front-end.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "front-end.name" . }}
    spec:
      containers:
      - name: {{ include "front-end.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.env.configMapName }}
              key: environment
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
