# Dev environment values
namespace: dev

replicaCount: 1
image:
  repository: amokscience/ntest
  pullPolicy: IfNotPresent
  tag: "dev-a0578c7"

env:
  HTTP_PORT: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

serviceAccount:
  create: true
  name: ntest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: dev.ntest.local

externalSecrets:
  enabled: false

monitoring:
  enabled: true
