apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: staging-

namespace: staging

patchesJson6902:
- target:
    group: v1
    version: v1
    kind: Service
    name: hello
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 8052

configMapGenerator:
- name: hello-config
  literals:
  - environment=staging
  - hello=Hello from Kubernetes!
