apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: staging-

namespace: staging

configMapGenerator:
- name: hello-config
  literals:
  - environment=staging
  - hello=Hello from Kubernetes!
