apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- external-secret.yaml

namePrefix: qa-

namespace: qa

patchesJson6902:
- target:
    group: v1
    version: v1
    kind: Service
    name: hello
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 8051

configMapGenerator:
- name: hello-config
  literals:
  - environment=qa
  - hello=Hello from qa Kubernetes!
