namespace: prod

externalSecrets:
  enabled: true
  awsRegion: us-west-2
  secretResourceName: hello-prod-config-secret
  awsSecretsManagerKeys:
    applicationConfig: config
  serviceAccountName: hello
