{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfb-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cfb-aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretResourceName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.awsSecretsManagerKeys.configKey }}
{{- end }}
