apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 2.4.3
    helm:
      releaseName: nginx-ingress
      values: |
        controller:
          replicaCount: 2
          service:
            type: LoadBalancer
          config:
            upstream-keepalive-connections: "32"
            upstream-keepalive-timeout: "86400"
            upstream-keepalive-requests: "1000"
            keep-alive: "86400"
            keep-alive-requests: "1000"
            client-header-timeout: "86400"
            client-body-timeout: "86400"
            keepalive-timeout: "86400"
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
    - /spec/preserveUnknownFields
  - group: ""
    kind: Service
    name: nginx-ingress-controller
    namespace: nginx-ingress
    jsonPointers:
    - /spec/ports/0/nodePort
    - /spec/ports/1/nodePort
  - group: coordination.k8s.io
    kind: Lease
    jqPathExpressions:
      - .spec