spec:
  project: default
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 2.4.3
    helm:
      releaseName: nginx-ingress
      values: |
        controller:
          service:
            type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  # ADD THIS BLOCK:
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
  # ADD syncOption:
  syncOptions:
  - CreateNamespace=true
  - RespectIgnoreDifferences=true  # Ensures ignores apply during sync
