{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hello-aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretResourceName }}
    creationPolicy: Owner
  data:
  - secretKey: config
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecretsManagerKeys.applicationConfig }}
{{- end }}
