{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ntest-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ntest-aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretResourceName }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.externalSecrets.awsSecretsManagerKeys }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}
  {{- end }}
{{- end }}
