apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

namespace: dev

configMapGenerator:
- name: sql-service-config
  literals:
  - environment=dev
