apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: staging-

namespace: staging

configMapGenerator:
- name: front-end-config
  literals:
  - environment=staging
